// Writes nginx's single-port Mongo routing config.
//
// One `map $ssl_server_name → container` plus one `listen <port> ssl` server
// block replaces the old one-stream-block-per-database (which required one
// published host port per database). nginx terminates TLS, reads the SNI
// hostname the client asked for (<db>-<id8>.mongo.<VPS_HOST>), and proxies to
// that database's container. Adding/removing a database only rewrites the map
// — the in-container inotify watcher (nginx/reload-watcher.sh) picks it up,
// so this works even when the orchestrator (Coolify) renames containers and
// `docker exec` can't find them.
//
// Postgres does NOT go through nginx at all anymore: its STARTTLS-style
// handshake has no SNI to route on, so the backend's own pgGateway service
// handles single-port PG routing.
const fs = require('fs');
const path = require('path');
const util = require('util');
const { execFile } = require('child_process');
const { mongoSniHost } = require('./urlGenerator');

const execFileP = util.promisify(execFile);

// Internal port the nginx container listens on for all Mongo traffic; the
// compose file maps ${MONGO_PUBLIC_PORT} on the host to this.
const NGINX_MONGO_LISTEN_PORT = 27017;

function streamDir() {
  return process.env.NGINX_STREAM_DIR || path.resolve(__dirname, '../../../nginx/stream.d');
}

function nginxContainer() {
  return process.env.NGINX_CONTAINER || 'customdb-nginx';
}

function sniConfigPath() {
  return path.join(streamDir(), 'customdb-sni.conf');
}

function ensureStreamDir() {
  fs.mkdirSync(streamDir(), { recursive: true });
}

function sniConfigText(entries) {
  const mapLines = entries
    .map(({ host, containerName }) => `  ${host} ${containerName}:27017;`)
    .join('\n');
  return `# Single-port Mongo routing — generated by the backend, do not edit.
# Client connects with TLS to <db>-<id8>.mongo.<host>:<public port>; the SNI
# hostname picks the container. Unknown hostnames land on 127.0.0.1:1 which
# refuses instantly.
map $ssl_server_name $customdb_mongo_upstream {
  hostnames;
  default 127.0.0.1:1;
${mapLines}
}

server {
  listen ${NGINX_MONGO_LISTEN_PORT} ssl;
  ssl_certificate     /etc/nginx/tls/customdb.crt;
  ssl_certificate_key /etc/nginx/tls/customdb.key;
  proxy_connect_timeout 5s;
  proxy_timeout 1h;
  proxy_pass $customdb_mongo_upstream;
}
`;
}

// Rebuild the whole routing config from database rows (the full active set —
// call with every non-deleted row; non-Mongo and legacy rows are skipped
// here). Also sweeps away the legacy per-port customdb-<port>.conf blocks
// from pre-single-port deployments.
async function syncMongoSni(rows) {
  ensureStreamDir();
  const existing = await fs.promises.readdir(streamDir()).catch(() => []);
  for (const f of existing) {
    if (f.startsWith('customdb-') && f.endsWith('.conf') && f !== 'customdb-sni.conf') {
      await fs.promises.unlink(path.join(streamDir(), f)).catch(() => {});
    }
  }
  const entries = rows
    .filter((r) => r.type === 'nosql' && r.containerName)
    .map((r) => ({ host: mongoSniHost(r), containerName: r.containerName }));
  await fs.promises.writeFile(sniConfigPath(), sniConfigText(entries), 'utf8');
  return entries.length;
}

// Best-effort reload. This exec path only works when the nginx container
// keeps its compose container_name (plain docker compose). Orchestrators
// like Coolify generate their own names, so the exec misses — that's fine:
// the nginx image runs an inotify watcher (nginx/reload-watcher.sh) that
// reloads itself whenever a stream config changes, so routing still updates.
async function reloadNginx() {
  try {
    const { stderr } = await execFileP('docker', ['exec', nginxContainer(), 'nginx', '-s', 'reload']);
    return { reloaded: true, stderr };
  } catch (err) {
    if (/No such container/i.test(err.stderr || err.message)) {
      console.log(`[nginx] no container named ${nginxContainer()} (orchestrator-managed names?) — relying on nginx's in-container config watcher`);
      return { reloaded: false, reason: 'no-nginx-container' };
    }
    throw err;
  }
}

module.exports = {
  syncMongoSni,
  reloadNginx,
  sniConfigPath,
  streamDir,
};
